apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lip3fu5l9-go
  janus-idp.io/tekton: lip3fu5l9-go
  backstage.io/kubernetes-id: lip3fu5l9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lip3fu5l9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
